#!/bin/bash

JAVA_HOME=/home/rbruno/software/jdk-11-shenandoah
JAVA_EXE="$JAVA_HOME/bin/java"

JVM_OPTS="$JVM_OPTS -server"
JVM_OPTS="$JVM_OPTS -XX:-TieredCompilation"
JVM_OPTS="$JVM_OPTS -XX:-UseBiasedLocking"
JVM_OPTS="$JVM_OPTS -XX:+UnlockExperimentalVMOptions"
JVM_OPTS="$JVM_OPTS -XX:+UseShenandoahGC"
JVM_OPTS="$JVM_OPTS -XX:ConcGCThreads=8"
JVM_OPTS="$JVM_OPTS -Xms8g"
JVM_OPTS="$JVM_OPTS -Xmx8g"
JVM_OPTS="$JVM_OPTS -Xlog:gc*,safepoint=info:file=/tmp/jvm.log::filecount=0,filesize=128m"

$JAVA_EXE $JVM_OPTS $*
