#!/bin/bash

JAVA_HOME=/home/rbruno/software/jdk-11-zgc
JAVA_EXE="$JAVA_HOME/bin/java"

JVM_OPTS="$JVM_OPTS -server"
JVM_OPTS="$JVM_OPTS -XX:-TieredCompilation"
JVM_OPTS="$JVM_OPTS -XX:-UseBiasedLocking"
JVM_OPTS="$JVM_OPTS -XX:+UnlockExperimentalVMOptions"
JVM_OPTS="$JVM_OPTS -XX:+UseZGC"
JVM_OPTS="$JVM_OPTS -XX:ConcGCThreads=8"
JVM_OPTS="$JVM_OPTS -Xms2g"
JVM_OPTS="$JVM_OPTS -Xmx2g"
JVM_OPTS="$JVM_OPTS -Xlog:gc*,safepoint=info:file=/tmp/jvm.log::filecount=0,filesize=128m"

$JAVA_EXE $JVM_OPTS $*
